### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by Acephalia** [JonathanFly/bark#18]
I am getting the out of memory issue on my 8GB card i noticed you had posted a comment about using `--use_smaller_models`. I installed the gui version from the instructions and then updated the files with the one in your repo. I am unsure where to put the `--use_smaller_models` would appreciate some help. Thank you.

**Comment by neezzzy** [comment]
maybe try this in your console:

```bash 
python bark_perform.py --use_smaller_models --text_prompt "It is a mistake to think you can solve any major problems just with potatoes... or can you? (and the next page, and the next page...)" --split_by_words 35 
```

**Comment by Acephalia** [comment]
I was trying to use the WebUI version that was linked on the description. It seems to launch via a ui.py file. Which I tried to add the parameters to but it just doesn’t seem to want to work. 

Could I potentially edit one of the py files to enable this always? 

Thank you for your time!

**Comment by powercore2000** [comment]
In the Suno version of bark I was able to edit the setup.py file next to the run.bat file and add os.environ["SUNO_USE_SMALL_MODELS"] = "True"

to activate small model mode, however, that does not work for this version of bark.

**Comment by huzidev** [comment]
> maybe try this in your console:
> 
> ```shell
> python bark_perform.py --use_smaller_models --text_prompt "It is a mistake to think you can solve any major problems just with potatoes... or can you? (and the next page, and the next page...)" --split_by_words 35 
> ```

Thanks that worked.

**Comment by Acephalia** [comment]
> SUNO_USE_SMALL_MODELS

This does work for the suno main version. Unfortunately I tried everything to make it work with this version but no luck.  Hopefully @JonathanFly might be able to provide some input when he has time.

**Comment by huzidev** [comment]
> 

You mean the web-ui version of bark which was created by Fictiverse or this bark infinity one?

**Comment by huzidev** [comment]
> Bark Infinity with webui. I found out about the webui through this fork. Infinity uses a different argument to set the smaller models. So I assume something is happening there because the global flag to set smaller models is in the infinity generation.py it just doesn’t trigger with the webui though for some reason.
> 
> I’m fairly sure someone who actually knows what they are doing will figure it out sooner or later the webui is also only in pre-release.

Sorry, I didn't understand about yours web-ui error since the link you've given above whic [WebUI version](https://github.com/Fictiverse/bark/releases) but this link was the same web-ui as I've told you about Fictiverse's bark and in this zip file we simply run the run.bat file which download all the required files for us and runs the ui for bark which will only generated voice as long as 12 to 13 seconds but his infinity one I haven't found any web-ui for this one 
If you've specific link for this infinity bark ui then please share that link so I can get to the root

**Comment by Acephalia** [comment]
> > Bark Infinity with webui. I found out about the webui through this fork. Infinity uses a different argument to set the smaller models. So I assume something is happening there because the global flag to set smaller models is in the infinity generation.py it just doesn’t trigger with the webui though for some reason.
> > I’m fairly sure someone who actually knows what they are doing will figure it out sooner or later the webui is also only in pre-release.
> 
> Sorry, I didn't understand about yours web-ui error since the link you've given above which [WebUI version](https://github.com/Fictiverse/bark/releases) but this link was the same web-ui as I've told you about Fictiverse's bark and in this zip file we simply run the run.bat file which download all the required files for us and runs the ui for bark which will only generated voice as long as 12 to 13 seconds but his infinity one I haven't found any web-ui for this one If you've specific link for this infinity bark ui then please share that link so I can get to the root

My bad should have explained better. You can run infinity bark on the same webui. Just download the latest commit from infinity and then unzip the files into the Fictiverse WebUi folder. Keep the same structure as the Fictiverse standard install and overwrite all files. This gets you the infinity version on webui if I am not mistaken. I unfortunately cant test any further than loading the ui and downloading a model up to the second generation phase, that is where I run out of VRAM. Which is why I have been trying to find a way to parse an argument to webui for use with infinity. 

Let me know how you go.

**Comment by JonathanFly** [comment]
> I am getting the out of memory issue on my 8GB card i noticed you had posted a comment about using `--use_smaller_models`. I installed the gui version from the instructions and then updated the files with the one in your repo. I am unsure where to put the `--use_smaller_models` would appreciate some help. Thank you.

Even the large models should work great on 8GB now in the latest version of Bark Infinity webui.
